import NavTabs from "@/components/Header/RegistrationAdviserNavTabs";
import ProfileTab from "@/components/Header/ProfileTab";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <div style={{ margin: 0 }}>
        <ProfileTab />
        {children}
      </div>
  );
}
